<a href="https://colab.research.google.com/github/jonrtaylor/FL_covid_data_notebooks/blob/master/FL_caseline_w_hospitalizations_to_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
###   CLICK "Open in Colab" to get started ###

###   CLICK 'Runtime' ABOVE AND THEN CLICK 'Run all'

###   YOU WILL SEE A DATA TABLE BETWEEN THE TOP CELL AND THE BOTTOM CELL SHOWING YOU THE DATA IN THIS NOTEBOOK

###   THE LAST CELL CREATES A CSV FILE WHICH WILL DOWNLOAD TO YOUR PC

###   PLEASE SHARE THIS RESOURCE IF YOU FIND IT HELPFUL


import pandas as pd
import requests

url_front = "https://services1.arcgis.com/CY1LXxl9zlJeBuRZ/ArcGIS/rest/services/Florida_COVID19_Case_Line_Data_NEW/FeatureServer/0//query?where=ObjectId>"
url_back = "&objectIds=&time=&resultType=standard&outFields=*&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=pjson&token="
object_id = 0
all_data = pd.DataFrame()
while object_id < 895999:
  JSONContent = requests.get(url_front + str(object_id) + url_back).json()
  df = pd.DataFrame([row['attributes'] for row in JSONContent['features']])
  df['Case1'] = pd.to_datetime(df.Case1, unit='ms')
  df['EventDate'] = pd.to_datetime(df.EventDate, unit='ms')
  df['ChartDate'] = pd.to_datetime(df.ChartDate, unit='ms')
  all_data = all_data.append(df, ignore_index=True)
  object_id += 32000
all_data

          County Age  ...           ChartDate ObjectId
0        Broward  24  ... 2020-08-08 05:00:00        1
1           Dade  61  ... 2020-07-21 05:00:00        2
2           Dade  51  ... 2020-07-21 05:00:00        3
3            Bay  19  ... 2020-07-24 05:00:00        4
4           Gulf  57  ... 2020-07-24 05:00:00        5
...          ...  ..  ...                 ...      ...
870547      Dade  28  ... 2020-07-30 05:00:00   870548
870548     Pasco  52  ... 2020-07-30 05:00:00   870549
870549      Dade  37  ... 2020-07-30 05:00:00   870550
870550  Okaloosa  28  ... 2020-07-30 05:00:00   870551
870551      Dade  29  ... 2020-07-30 05:00:00   870552

[870552 rows x 16 columns]

In [4]:
all_data.ObjectId.nunique()

870552

In [ ]:
### Example to show how to filter for a certain County

all_data[all_data['County'] == "Palm Beach"]

            County Age  ...           ChartDate ObjectId
16      Palm Beach  25  ... 2020-08-10 05:00:00       17
38      Palm Beach  26  ... 2020-06-23 05:00:00       39
81      Palm Beach  27  ... 2020-07-13 05:00:00       82
112     Palm Beach  57  ... 2020-07-12 05:00:00      113
115     Palm Beach  48  ... 2020-10-21 05:00:00      116
...            ...  ..  ...                 ...      ...
807285  Palm Beach  54  ... 2020-06-24 05:00:00   807286
807291  Palm Beach  61  ... 2020-08-03 05:00:00   807292
807321  Palm Beach  26  ... 2020-09-01 05:00:00   807322
807353  Palm Beach  42  ... 2020-07-19 05:00:00   807354
807399  Palm Beach  66  ... 2020-09-11 05:00:00   807400

[52779 rows x 16 columns]

In [ ]:
all_data.to_csv('FL_caseline_file.csv', index=False)
from google.colab import files
files.download('FL_caseline_file.csv')

In [ ]:
#download only a single county
df2 = all_data[all_data['County'] == "Alachua"].copy()
df2.to_csv('Alachua_caseline_file.csv', index=False)
files.download('Alachua_caseline_file.csv')